### ISSUE TITLE
Need i18n exporter script

### ISSUE THREAD

**Issue by andrewshadura** [lvee/lvee-engine#1]
There's currently no way to export the flattened database i18n representation back to YAML to update the translation sources. I performed a semi-manual export with

``` sql
select concat(`language_id`,'.', concat_ws(': ',concat(`key`,"[",`pluralization_index`,"]"),concat('"',`value`,'"'))) from translations order by `language_id`, `key` into outfile "/tmp/translations.yml";
```

Which resulted in a file looking like this:

``` yaml
be.activerecord.errors.messages.accepted[1]: "трэба прыняць"
be.activerecord.errors.messages.blank[1]: "трэба запоўніць"
be.activerecord.errors.messages.confirmation[1]: "не адпавядае ўпісанаму паролю"
…
```

And then processed the output with this awk script: https://gist.github.com/andrewshadura/cff37d668903bb1938c31ad90a3053ab. That gave me almost usable almost YAML file I could manually merge.

That however is very error-prone, so something better should be developed in its stead.

**Comment by alex-liberty** [comment]
Variant of my exporter [script](https://gist.github.com/alex-liberty/7556b55e60397893b034eb8033e2fada)

Copy this code to `/lib/tasks/export_languages.rake` and run `rake export_languages`
