### ISSUE TITLE
Bug: can't change personal data of an account

### ISSUE THREAD

**Issue by YakovL** [lvee/lvee-engine#27]
How I reproduce the problem:
1. open lvee.org (in Vivaldi or Chrome), login (YakovL), go to edit personal data
2. edit the "FOSS projects" field, hit "update"

What actually happens: the page shows red box headed `errors.template.header` with content

> errors.template.body
> * Login уже существует
> * Email уже существует

and the update is not saved.

What is expected to happen: the update is saved.

Actually, this is not a problem of the "FOSS projects" field specifically, just can't update the account data.

**Comment by alex-liberty** [comment]
You register the user on a website with the same data three times(I don't know how)

**Comment by alex-liberty** [comment]
@YakovL inactive users was deleted
