### ISSUE TITLE
Could not recover my password at lvee.org

### ISSUE THREAD

**Issue by chubin** [lvee/lvee-engine#36]
I am not sure that here is the right place to to submit this bug, but I could not manage to find any email on lvee.org where I could submit it.

I think that I have been a registered lvee.org user since many years (since 2007 or so), but I haven't been using the site since that.

Today I tried to recover my password, but it didn't work: the site says to me that a recover email was sent, but nothing happens after that (and I get no emails). I tried t create a new user using the same email, but it didn't work either ("email has been already taken").

Could you please check, what is the root of the problem, and could my old registration be recovered (or completely removed, because I have a new one now).

My original email: `igor@chub.in`
Email that I've used for the latest registration: `igor.m@chub.in`

Thank you!

**Comment by alex-liberty** [comment]
@chubin Logs is empty. I sent the letter again.
Please check your email(igor@chub.in) again. Maybe mail in spam

**Comment by chubin** [comment]
Thank you very much for the answer.
No, I've not received anything.
I suppose that if you just send me a email directly (from your personal email account)
I will get it without any problem (as I get the rest of my emails except the emails from lvee.org).

**Comment by alex-liberty** [comment]
@chubin sent on igor@chub.in

**Comment by chubin** [comment]
Thank you!
